# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:38
from __future__ import unicode_literals

from datetime import timezone
import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0008_auto_20151211_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employeeskill',
            old_name='customerOrder',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeeskill',
            old_name='expereince',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='employeeskill',
            old_name='product',
            new_name='skill',
        ),
        migrations.AddField(
            model_name='department',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 15, 37, 13, 599513, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 26, 15, 37, 13, 599513, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 15, 37, 30, 195187, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=django_fsm.FSMField(default='hired', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 26, 15, 38, 19, 50022, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('U', 'Unknown')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together=set([('employee', 'skill')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='employeeskill',
            order_with_respect_to='employee',
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='commerce.Department'),
        ),
    ]
