# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20160126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
