# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_exppatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exppatient',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpPatient',
        ),
    ]
